# Generated by Django 5.1.5 on 2025-02-02 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0002_alter_faq_answer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faq',
            options={'ordering': ['id']},
        ),
    ]
